slug = '0x03-prototype-pollution'
title = '0x03 Prototype Pollution'
description = 'Finding a way into the internal infrastructure. Prototype pollution, popping shells, for fun, and for profit.'
draft = false
image = "thumbnail.png"
categories = ["Domain Compromise Series", "Web Hacking", "Linux", "Windows", "Active Directory", "Hacking", "Exploits"]
tags = ["Prototype Pollution", "Poisoning", "Injection", "Command Injection", "IMAP",  "Pivoting", "Persistence", "External Pentest", "Credentials Reuse", "Developers"]
date = '2023-10-13'
toc = true
authors = ["Krystian Bajno"]