slug = '0x05-tiocsti-injection'
title = '0x05 - TIOCSTI injection'
description = 'Abusing TIOCSTI to manipulate process file descriptors and execute arbitrary commands.'
draft = false
image = "thumbnail.jpeg"
categories = ["Linux", "Hacking"]
tags = ["Kernel"]
date = '2023-12-30'
toc = true
authors = ["Krystian Bajno"]