slug = '0x05-tiocsti-injection'
title = '0x05 - TIOCSTI injection'
description = 'TIOCSTI abuse. Manipulate process file descriptors and execute arbitrary commands using ioctl.'
draft = false
image = "thumbnail.jpeg"
categories = ["Linux", "Hacking"]
date = '2023-12-30'
toc = true
authors = ["Krystian Bajno"]