+++
slug = '0x02-terminal-injection'
title = '0x02 Terminal Injection'
description = 'What happens when you run scripts without checking the contents properly?'
draft = false
image = "thumbnail.jpeg"
categories = ["Linux", "Windows", "Exploits", "Hacking"]
date = '2021-06-07'
+++
