name: Trigger deploy in blog repository

on: 
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.DEPLOY_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'krystianbajno',
            repo: 'baycode-news-hugo',
            workflow_id: 'hugo.yml',
            ref: 'main'
          })