slug = '0x04-lateral-movement'
title = '0x04 Lateral Movement'
description = 'Exploiting the Active Directory environment and compromising the domain controller.'
draft = false
image = "thumbnail.png"
categories = ["Domain Compromise Series", "Active Directory", "Windows", "Malware Development", "Hacking"]
tags = ["Enumeration", "Reports", "Password Cracking", "Kerberoasting", "Credentials reuse", "AS-REP Roasting", "Kerberos", "RDP", "WinRM", "Persistence", "Print Nightmare", "SMB Relay", "LSASS", "Delegation", "Golden Ticket", "Lateral Movement", "Persistence", "External Pentest", "Credentials Reuse", "Antivirus Evasion"]
date = '2023-11-02'
toc = true
authors = ["Krystian Bajno"]