slug = '0x04-lateral-movement'
title = '0x04 Lateral Movement'
description = 'Exploiting the Active Directory environment and compromising the domain controller.'
draft = false
image = "thumbnail.png"
categories = ["Domain Compromise Series", "Active Directory", "Windows", "Hacking"]
date = '2023-11-02'
toc = true